name: Publish to GitHub Packages

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #     - demo
  #     - release/**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: https://npm.pkg.github.com/
          scope: "@gsa-tts"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm run build

      - name: Authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Get commit hash
        id: commit
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Get branch name
        id: branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Publish all packages with commit hash tag
        run: pnpm -r publish --no-git-checks --tag ${{ env.COMMIT_HASH }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag all packages with branch name
        run: pnpm -r dist-tag add @gsa-tts/*@$(pnpm list --depth=-1 --json | jq -r '.[].version') ${{ env.BRANCH_NAME }}

      - name: Update latest tag (only for main)
        if: github.ref == 'refs/heads/main'
        run: pnpm -r dist-tag add @gsa-tts/*@$(pnpm list --depth=-1 --json | jq -r '.[].version') latest
